name: Update Modules List

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Fetch and format modules
        run: |
          # Fetch JSON from API
          MODULES_JSON=$(curl -s https://www.wisp.tools/api/get-modules)

          # Check if curl succeeded
          if [ -z "$MODULES_JSON" ]; then
            echo "Failed to fetch modules"
            exit 1
          fi

          # Create markdown content
          README_TEMPLATE=$(cat ./profile/TEMPLATE.md)
          echo -e "$README_TEMPLATE" > profile/README.md

          # Process JSON with jq and append table to README
          echo "$MODULES_JSON" | jq -r '
            def table_row($name; $description; $slug): 
              "| \($name) | \($description) | [Visit](https://www.wisp.tools/mod/\($slug)) |\n";
            def table_header: 
              "| Name | Description | Link |\n| --- | --- | --- |\n";
            
            table_header + 
            (map(table_row(.name; .description; .slug)) | add)
          ' >> profile/README.md

          # Append footer
          TODAY=$(date +"%b %d, %Y")
          echo -e "\n`List last fetched on $TODAY`" >> profile/README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -f profile/README.md
          git commit -m "apiUpdate(README): Update modules list"
          git push
