name: Update README

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Update README
        run: |
          echo -e "# Hello World!\n\nThe current time of this readme update is $(date +%s)" > profile/README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add profile/README.md
          git commit -m "Update README with current time [skip ci]"
          git push
